# Generated by Django 4.1.7 on 2023-03-27 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Title Category')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='app_media.mediacategorymodel')),
                ('subcategories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_goods.goodcategorymodel')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
