# Generated by Django 4.1.7 on 2023-03-28 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodcategorymodel',
            name='subcategories',
        ),
        migrations.AddField(
            model_name='goodcategorymodel',
            name='sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='app_goods.goodcategorymodel'),
        ),
    ]
