# Generated by Django 4.1.7 on 2023-03-28 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0002_remove_goodcategorymodel_subcategories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(max_length=1000, verbose_name='Price')),
                ('count', models.IntegerField(max_length=1000, verbose_name='Count')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('freeDelivery', models.BooleanField(default=False)),
                ('images', models.ImageField(blank=True, null=True, upload_to='media/goods/items', verbose_name='Images')),
                ('tags', models.CharField(max_length=100, verbose_name='Tags')),
                ('reviews', models.IntegerField(max_length=1000, verbose_name='Reviews')),
                ('rating', models.FloatField(blank=True, default=0, max_length=1000, null=True, verbose_name='Rating')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_goods.goodcategorymodel', verbose_name='Category')),
            ],
        ),
    ]
