# Generated by Django 4.1.7 on 2023-03-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0003_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='count',
            field=models.IntegerField(verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='items',
            name='reviews',
            field=models.IntegerField(verbose_name='Reviews'),
        ),
    ]
