# Generated by Django 4.1.7 on 2023-03-28 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0004_alter_items_count_alter_items_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='category',
        ),
        migrations.AddField(
            model_name='goodcategorymodel',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_goods.items'),
        ),
    ]
