# Generated by Django 4.1.7 on 2023-03-28 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0005_remove_items_category_goodcategorymodel_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
    ]
