# Generated by Django 4.1.7 on 2023-03-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0006_alter_items_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodcategorymodel',
            name='items',
        ),
        migrations.AddField(
            model_name='goodcategorymodel',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='app_goods.items'),
        ),
    ]
