# Generated by Django 4.1.7 on 2023-03-28 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_media', '0001_initial'),
        ('app_goods', '0007_remove_goodcategorymodel_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodcategorymodel',
            name='image',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='app_media.mediacategorymodel'),
        ),
    ]
