# Generated by Django 4.1.7 on 2023-03-28 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0008_alter_goodcategorymodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodcategorymodel',
            name='items',
        ),
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_goods.goodcategorymodel'),
        ),
    ]
