# Generated by Django 4.1.7 on 2023-03-28 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0009_remove_goodcategorymodel_items_items_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_goods.goodcategorymodel', verbose_name='Category'),
        ),
    ]
